module.exports = {
  preset: 'ts-jest',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '**/*.(t|j)s',
    '!**/*.module.ts',         
    '!main.ts',                
    '!**/dto/**',              
    '!**/constants/**',        
    '!**/interfaces/**',       
    '!**/models/**',           
    '!**/__mocks__/**',        
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  coverageReporters: ['text', 'lcov'],
  coveragePathIgnorePatterns: [
    '.module.ts', 'main.ts', 'dto', 'models',
    '/node_modules/',
    '/dist/',
  ],
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
